name: Deploy FastAPI + Postgres

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          set -e

          echo "Go to backend folder"
          cd ~/intelliterminalapis

          echo "Pull latest code"
          git pull origin main

          echo "Ensure network exists"
          docker network inspect appnet >/dev/null 2>&1 || docker network create appnet

          # -----------------------
          # POSTGRES SETUP
          # -----------------------
          echo "Setup Postgres"
          if [ "$(docker ps -aq -f name=postgres-db)" ]; then
            echo "Postgres exists → starting"
            docker start postgres-db
          else
            echo "Creating Postgres container"
            docker run -d \
              --name postgres-db \
              --network appnet \
              --env-file .env \
              -v postgres_data:/var/lib/postgresql/data \
              -p 5432:5432 \
              --restart always \
              postgres:15
          fi

          echo "Wait for Postgres"
          sleep 5

          # -----------------------
          # FREE PORT 8000
          # -----------------------
          echo "Free port 8000 if occupied"
          docker ps --filter "publish=8000" -q | xargs -r docker stop
          docker ps -a --filter "publish=8000" -q | xargs -r docker rm

          # -----------------------
          # FASTAPI DEPLOY
          # -----------------------
          echo "Remove old FastAPI container"
          docker rm -f fastapi-app 2>/dev/null || true

          echo "Build FastAPI image"
          docker build -t fastapi-app .

          echo "Run FastAPI container"
          docker run -d \
            --name fastapi-app \
            --network appnet \
            -p 8000:8000 \
            --env-file .env \
            --restart always \
            fastapi-app

          echo "Deployment completed successfully 🚀"