script: |
  echo "Go to backend folder"
  cd ~/intelliterminalapis

  echo "Pull latest code"
  git pull origin main

  echo "Ensure network exists"
  docker network inspect appnet >/dev/null 2>&1 || docker network create appnet

  
  # -----------------------
  # POSTGRES SETUP
  # -----------------------
  if [ "$(docker ps -aq -f name=postgres-db)" ]; then
    echo "Postgres exists, starting..."
    docker start postgres-db
  else
    echo "Creating Postgres..."
    docker run -d \
      --name postgres-db \
      --network appnet \
      --env-file .env \
      -v postgres_data:/var/lib/postgresql/data \
      -p 5432:5432 \
      --restart always \
      postgres:15
  fi

  echo "Wait for Postgres to be ready..."
  sleep 5

  # -----------------------
  # FASTAPI SETUP
  # -----------------------
  echo "Stop old FastAPI (if exists)"
  docker rm -f fastapi-app || true

  echo "Build FastAPI"
  docker build -t fastapi-app .

  echo "Run FastAPI"
  docker run -d \
    --name fastapi-app \
    --network appnet \
    -p 8000:8000 \
    --env-file .env \
    --restart always \
    fastapi-app

  echo "Deployment done"